### ISSUE TITLE
Broken since release 4.0

### ISSUE THREAD

**Issue by bwwinthehouse** [react-component/calendar#81]
When I try to build

```/Users/bwhite/web-watchtower/node_modules/core-tasks/utils.js:53
      throw err;
            ^
Error: Cannot find module 'react-dom' from '/Users/bwhite/web-watchtower/node_modules/rc-calendar/node_modules/rc-util/lib/Dom'
    at /Users/bwhite/web-watchtower/node_modules/core-tasks/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/bwhite/web-watchtower/node_modules/core-tasks/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/bwhite/web-watchtower/node_modules/core-tasks/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/bwhite/web-watchtower/node_modules/core-tasks/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/bwhite/web-watchtower/node_modules/core-tasks/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/bwhite/web-watchtower/node_modules/core-tasks/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)```

**Comment by benjycui** [comment]
If you use webpack, you can set react-dom as [external](https://webpack.github.io/docs/library-and-externals.html#examples). But I don't know how to do this in browserify. 

But you can google it, or try webpack.

**Comment by yiminghe** [comment]
in your project root directory, run

```
tnpm install react@0.14.x react-dom@0.14.x --save
```
